(require '[pcp :as pcp])
(pcp/now)
(pcp/html [:div "pcp"])
(pcp/render-html [:div "pcp"])
(pcp/render-html-unescaped [:div "<p>pcp</p>"])
(pcp/secret "HAHA")
(pcp/clear :test)
(pcp/persist :test (fn [] (range 51)))
(pcp/response 200 (apply + (pcp/persist :test (fn [] nil))) "text/plain")