name: branches

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:

  jvm:
    # ubuntu 18.04 comes with lein + java8 installed
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: 'true'
 
      - name: Cache deps
        uses: actions/cache@v1
        id: cache-deps
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
                ${{ runner.os }}-maven-

      - name: Fetch deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          lein deps

      - name: Tests and coverage
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          PCP_KEYDB: "./test-resources/pcp-db"
        run: |
          lein cloverage